/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ABackTop: typeof import('ant-design-vue/es')['BackTop']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APageHeader: typeof import('ant-design-vue/es')['PageHeader']
    APagination: typeof import('ant-design-vue/es')['Pagination']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ARow: typeof import('ant-design-vue/es')['Row']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATag: typeof import('ant-design-vue/es')['Tag']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATimeline: typeof import('ant-design-vue/es')['Timeline']
    ATimelineItem: typeof import('ant-design-vue/es')['TimelineItem']
    Comicreader: typeof import('./src/components/comicreader.vue')['default']
    Loading: typeof import('./src/components/loading.vue')['default']
    Loading1: typeof import('./src/components/loadingList/loading1.vue')['default']
    Loading2: typeof import('./src/components/loadingList/loading2.vue')['default']
    Loading4: typeof import('./src/components/loadingList/loading4.vue')['default']
    Loading5: typeof import('./src/components/loadingList/loading5.vue')['default']
    Loading6: typeof import('./src/components/loadingList/loading6.vue')['default']
    Loading7: typeof import('./src/components/loadingList/loading7.vue')['default']
    Loading8: typeof import('./src/components/loadingList/loading8.vue')['default']
    Previewaudio: typeof import('./src/components/previewaudio.vue')['default']
    Previewaudiolist: typeof import('./src/components/previewaudiolist.vue')['default']
    Previewhtml: typeof import('./src/components/previewhtml.vue')['default']
    Previewimg: typeof import('./src/components/previewimg.vue')['default']
    Previewtext: typeof import('./src/components/previewtext.vue')['default']
    Previewvideo: typeof import('./src/components/previewvideo.vue')['default']
    Repeatcard: typeof import('./src/components/repeatcard.vue')['default']
    Repeatpageturning: typeof import('./src/components/repeatpageturning.vue')['default']
    Repeatpagination: typeof import('./src/components/repeatpagination.vue')['default']
    Repeatpositioner: typeof import('./src/components/repeatpositioner.vue')['default']
    Repeattable: typeof import('./src/components/repeattable.vue')['default']
    Repeatyintable: typeof import('./src/components/repeatyintable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
